### PR TITLE
#542 cp.props work

### PR DESCRIPTION
**Pull request by randomeizer**

### CODE REVIEW

**Comment by randomeizer** [comment]
Take a look when you can, and we can get this sucker closed off.

**Comment by latenitefilms** [comment]
Note to self: not sure if this is related to this specific branch or not but...

```
2017-04-28 13:06:18: ********
2017-04-28 13:06:18: 13:06:18 ERROR:   LuaSkin: hs.hotkey callback error: ...CommandPost/src/plugins/finalcutpro/browser/playhead.lua:114: attempt to index a nil value (local 'playhead')
stack traceback:
	...CommandPost/src/plugins/finalcutpro/browser/playhead.lua:114: in function <...CommandPost/src/plugins/finalcutpro/browser/playhead.lua:103>
	(...tail calls...)
2017-04-28 13:06:18: ********
```

**Comment by latenitefilms** [comment]
@randomeizer - the browser playhead is definitely broken in this branch - works fine in `develop`. I've tried to fault find, but haven't work out why it's broken yet.

**Comment by latenitefilms** [comment]
@randomeizer - Never mind. Was just missing a `return`. Will keep testing!

**Pull request merged**
