### PR TITLE
#1012 - Final Cut Pro Viewer Grid & Still Frames

### LINKED ISSUE #948: Add Final Cut Pro Viewer Buffer
Add shortcuts for saving the current frame in the Viewer to a buffer, and shortcuts for restoring that current frame over the top of the Viewer as an overlay. Possibly also add the ability to crop the overlay horizontally and vertically.

### LINKED ISSUE #1012: Final Cut Pro Viewer Grid
Adam Schoales [suggests](https://www.facebook.com/groups/commandpost/permalink/1981163592139342/):

> Okay, so I'm not sure if this would even be possible, but one of my favourite features in Photoshop (and to some extent After Effects) is the one screen rules and grid/dragable guides.
> Is that something that'd be possible to add via Command Post? FCP is pretty good with the snapping guides but for aligning elements to other elements having the ability to drag in a guide would be amazing, without having to resort to using a generator/text effect

### PR DESCRIPTION
**Pull request by latenitefilms**
- Added contextual menu to top of viewer allowing you to toggle grids
and still frames. These features can also be trigged via actions.
- Closes #1012
- Closes #948

### CODE REVIEW

**Comment by latenitefilms** [comment]
@randomeizer - Did you want to have a quick look and review of this, and if you get time, see if you can add a notifier to the FCP Viewer, so that we can trigger a callback when the viewer is resized?

Feel free to add any other guides, grids, etc. you think might be handy!

I might add a "custom overlay" - so users can import their own transparent image to use as an overlay.

**Comment by latenitefilms** [comment]
Would also be handy to add "letterboxing" over a 16:9 frame, and 4:3 safe lines.

**Comment by randomeizer** [comment]
What might be useful is taking a snapshot of the viewer that can be
overlaid, with a draggable bar that lets you select how much of the
snapshot to show. This could then be used while colour grading to get an
image of the next/previous shot to match with.

Could also have the option of covering the event viewer, if it's available.

**Comment by latenitefilms** [comment]
@randomeizer - It already does this - but has "Layout" presets instead of a draggable bar. Maybe we could add a "Draggable" option?

I didn't think about the Event Viewer - but that's a great idea.

**Comment by latenitefilms** [comment]
@randomeizer - Another feature request one of our editors, Kevin, just suggested is a "horizon" tool like you have in Photoshop when you hold down COMMAND and use the crop tool. Basically if COMMAND is held down and you click and drag, it draws a "horizon" line on the image, and then when you release it would update the rotation angle in the Inspector.

**Comment by randomeizer** [comment]
Is the horizon always level with the bottom of the image?

**Comment by latenitefilms** [comment]
@randomeizer - Here's what it does in Photoshop:

horizon

**Comment by randomeizer** [comment]
Ah, got it.

**Pull request merged**
