### PR TITLE
#362 - Console update

### PR DESCRIPTION
**Pull request by randomeizer**
Main changes:
* Simplified the right-click menu
* Moved options into the main menu, under 'Console'
* Added the 'Manage Hidden Items...' view, which will toggle hidden/visible for items when pressing enter, rather than activating it.

### CODE REVIEW

**Comment by latenitefilms** [comment]
All seems great to me! Thanks @randomeizer !!

As discussed, I'd like to restore the functionality where you user can show/hide the audio AND/OR the video effects, but apart from that, it all seems to be working as good as it was originally.

I'll leave it up to you as to whether or not you want to merge this pull request, and create a new issue for the audio/video effects or not.

**Comment by randomeizer** [comment]
I've pushed a fix with them split into separate categories. Can you check it?

As a side effect of this overall update, we can now create 'commandpost://' URLs to run commands, trigger title/effect/generators/etc, and run menu buttons. Not exactly sure where it will be useful, but you never know ;)

**Comment by latenitefilms** [comment]
> I've pushed a fix with them split into separate categories. Can you check it?

Legend, thank you! All seems to work great here!

> As a side effect of this overall update, we can now create 'commandpost://' URLs to run commands, trigger title/effect/generators/etc, and run menu buttons. Not exactly sure where it will be useful, but you never know ;)

It might come in handy for #153!

**Comment by randomeizer** [comment]
Yeah, could do.

**Pull request merged**
