### PR TITLE
#546 - Make Hacks Shortcuts self contained

### PR DESCRIPTION
**Pull request by randomeizer**
Because the `Hacks Shortcuts` plugin had tenticles in the 'Welcome Screen' and the Preferences panel, this ended up spilling across into some improvements in those plugins also. Key changes to test:

## Hacks Shortcuts
* Self-contained. Can be disabled in the Plugins panel.
* 'Launch Final Cut Pro' was removed from the FCPX Command Editor UI, since it is a Global command. Only commands that are directly relevant to FCPX are managed in the Command Editor now. This will be more useful as we start adding support for apps other than FCPX.
* If changes are made to the plists between versions, the plugin will now detect those changes and use the Welcome/Setup plugin to prompt the user to either choose FCPX or CP to manage those shortcuts.

## Preferences
* Shortcuts panel now groups shortcuts into 'command groups', selectable via a drop-down
* When Hacks Shortcuts is enabled, the default editor is replaced with a message to use FCPX.
* General layout of the table/headings improved.

## Welcome (aka Setup)
* Renamed `cp.welcome.manager` to `cp.setup`. This is because the plugin may prompt the user at any time when setup configuration needs to be run (for example, accessibility is disabled, a new version of CP has plugins requiring configuration, etc).
* Setup panel creation is simplified and condensed.
* The various `panel` plugins have been generally moved into the plugin that needs to be set up, making it simpler to enable/disable/uninstall specific plugins if required.
* The buttons and 'progress dots' are now consistently at the same position on the bottom of the window.

## Miscellaneous
* Created the `core.accessibility` plugin, which manages checking that CP has been granted accessibility permissions.
* Some improvements to `cp.plugins`, including support for a `disabled` method on plugins that is called when the plugin is disabled, allowing cleanup.

### CODE REVIEW

**Comment by latenitefilms** [comment]
@randomeizer - Do you have a slight delay now when changing tabs in the Preferences panel?

**Comment by randomeizer** [comment]
Define delay?

**Comment by latenitefilms** [comment]
If I'm on the Shortcuts panel and click on the Menubar panel, there is a slight delay on my laptop as the panel refreshes. Rather than instantly loading the Menubar panel, the panel goes grey (for the height of the Shortcuts panel) and white for the height of the Menubar panel. Attached is a screenshot that I've tried to grab during this delay.

screen shot 2017-05-19 at 10 02 31 pm

**EDIT:** After doing a Preferences trash on CommandPost this delay doesn't seem to happen anymore, so all seems good? Although we might need to suggest to beta testers that they trash preferences before use?

Some other minor things:

* On a fresh install of CommandPost, the menubar icon appear very briefly before disappearing and the welcome/setup screen appears. Even though it's only for a brief instant - it probably shouldn't do this, as it might confuse users?

* On a fresh install, if you click the **USE COMMANDPOST** button the _"Disabling CommandPost Shortcuts in Final Cut Pro requires your Administrator password. Do you want to continue?"_ appears - which is shouldn't? Although... maybe I already had Hacks shortcuts installed? In that case... maybe this panel should be skipped?

* After the welcome/setup process is complete, if later down the line you disable Accessibility Permissions, the Accessibility Panel opens up again - but the **QUIT** button doesn't work.

* I wonder if when you enable Accessibility for CommandPost, we should automatically close **System Preferences**?

* It might be a bit confusing that the menubar icon doesn't actually appear until you press **CLOSE** on the last welcome panel. Maybe the menubar icon should load when this final welcome panel loads?

* If you enable **Control CommandPost Shortcuts within Final Cut Pro** with Final Cut Pro closed, the Shortcuts panel doesn't update (i.e. the **Final Cut Pro X** shortcuts panel isn't disabled until after you restart CommandPost).

* If I try to disable **Control CommandPost Shortcuts within Final Cut Pro** or **Enable Developer Mode**, but click **No** at the dialog box, the checkbox doesn't re-enable itself. My suggestion would be to use Javascript to instantly set the checkbox to its original state whenever you click one, then leave it up to the Lua callback to update the state if required.

* Although I really like the fact that the buttons and progress dots stay the same position on the bottom of the frame, the Welcome panels seem very unbalanced at the moment. Maybe we just need to centre the main text vertically on the screen?

screen shot 2017-05-19 at 9 52 51 pm

Awesome work with all this @randomeizer ! Looking REALLY nice!! THANK YOU!

**Comment by randomeizer** [comment]
I'll try to address each comment...let me know if I miss anything.

* Icon appearance: I actually think the icon should be around permanently, but with only very basic options (Help, Quit, etc).
* Use CommandPost: It would prompt you to uninstall if you already had it installed. With regards to skipping the step if it's already installed, I think we should still ask the question if it's the 'first run' (or you nuked settings). In this case, it would most likely still prompt you anyway since the plists have changed, and you would need to reinstall them.
* Accessibility: I'll check out the Quit button. With regards to closing the System panel, maybe? It had occurred to me, but I'm 50/50 on it. Maybe only close it if it was not already open before checking accessibility?
* Menu Icon on the last Panel: This is one reason I'm thinking we always have the icon there, just with limited options initially. On slightly separate topic, I'm thinking that the FCPX menu items should only appear when FCPX is the active application. Otherwise, it will get very crowded when we start adding other apps. But that should be implemented in a separate issue.
* Enabling Hacks Shortcuts without restarting: I'm thinking that CP should reload regardless - I'm not 100% sure the shortcuts will reassign correctly. Thinking about it, I'm not sure that it currently takes into account changes to shortcuts made in the FCPX Command Editor.
* Cancelling Hacks Shortcuts: You don't think it will seem weird that the checkbox flips back to unchecked? Why not just update it from LUA if it gets canceled? 
* Welcome panels: Centring vertically is actually [kind of tricky](http://vanseodesign.com/css/vertical-centering/). I guess the simplest way would be to add a &lt;br/&gt; in front of specific bits of text you want to push down. That said, it's current position doesn't bother me - I personally felt it was too spaced out previously anyway.

**Comment by latenitefilms** [comment]
> Icon appearance: I actually think the icon should be around permanently, but with only very basic options (Help, Quit, etc).

Agreed. Let's make the icon permanent.

> Use CommandPost: It would prompt you to uninstall if you already had it installed. With regards to skipping the step if it's already installed, I think we should still ask the question if it's the 'first run' (or you nuked settings). In this case, it would most likely still prompt you anyway since the plists have changed, and you would need to reinstall them.

No worries, that makes sense.

> Accessibility: I'll check out the Quit button. 

Sweet.

> With regards to closing the System panel, maybe? It had occurred to me, but I'm 50/50 on it. Maybe only close it if it was not already open before checking accessibility?

Agreed - we should check to see if it's already open, and if it's not, we open it, then once CommandPost has accessibility permissions, we close it. However - I'm not sure we can detect if it's already open without GUI Scripting permissions?

> On slightly separate topic, I'm thinking that the FCPX menu items should only appear when FCPX is the active application. Otherwise, it will get very crowded when we start adding other apps. But that should be implemented in a separate issue.

Agreed - however, we should probably split some things out from Final Cut Pro, to the Core, such as Mobile Notifications and Console, as I feel like these are things that we could eventually utilise in multiple applications? Everything in the "MEDIA IMPORT" section can go (when FCPX is not active). Virtual Touch Bar, and Voice Commands we should probably re-design so it can be used without Final Cut Pro open.

> Enabling Hacks Shortcuts without restarting: I'm thinking that CP should reload regardless - I'm not 100% sure the shortcuts will reassign correctly. Thinking about it, I'm not sure that it currently takes into account changes to shortcuts made in the FCPX Command Editor.

Well, currently it doesn't seem to restart CommandPost when you enable Hacks shortcuts, so we should fix this in this issue before merging into develop.

> Cancelling Hacks Shortcuts: You don't think it will seem weird that the checkbox flips back to unchecked? Why not just update it from LUA if it gets canceled?

It is a bit weird, but the only reason I suggest this is because if flipping a checkbox opens up a dialog, then a user could always clip away from the dialog box and click it again, which will just throw things out of whack. Maybe rather than "flip" it we should "disable" it until the Lua callback takes place, and updates it's value accordingly?

> Welcome panels: Centring vertically is actually kind of tricky.

We could just use a CSS Table? Pretty much every welcome panel is the same layout - icon at the top, buttons and progress dots at the bottom, text in the middle - and it's a fixed size, so a CSS Table makes sense?

Apart from these notes, everything else seems to be working fine, so once these minor tweaks are done, I reckon we're all good to merge into develop, and push out another release!

**Comment by randomeizer** [comment]
There's a bit involved in rearranging the menus to make the 'icon always on' work properly, so I've created a separate issue for that (#650)

I think we should be able to check if the System Prefs app is open via the standard `hs.application` (vs. `axuielement`), but yeah, I'm not sure if it's accessible without getting Accessibility permissions first...

There is a basic issue with panels not updating in the Prefs Panel if something happens in one panel that affects another one.

Disabling the checkbox could be a reasonable option. Once the action is completed on the LUA side, it will have to enable and update the status for the checkbox again.

Which text would you want centred exactly? The titles? or just the paragraphs?

**Comment by randomeizer** [comment]
So, I think the list of stuff on this issue is:
- [x] Accessibility "Quit" button
- [x] Close System Prefs after Accessibility set (if possible)
- [ ] Reloading/resetting CP after Hacks Shortcuts is changed in Prefs
- [ ] Disabling Prefs checkbox while waiting for LUA to finish
- [ ] Welcome panel layout?

**Comment by latenitefilms** [comment]
> There's a bit involved in rearranging the menus to make the 'icon always on' work properly, so I've created a separate issue for that (#650)

Sweet!

> I think we should be able to check if the System Prefs app is open via the standard hs.application (vs. axuielement), but yeah, I'm not sure if it's accessible without getting Accessibility permissions first...

It looks like `hs.application.find("System Preferences"):kill()` works without Accessibility permissions, so this should all be possible.

> There is a basic issue with panels not updating in the Prefs Panel if something happens in one panel that affects another one.

It might be worth you having a look at how I handled this in the Watch Folder panel - it's not exactly eloquent - but it seems to work.

> Disabling the checkbox could be a reasonable option. Once the action is completed on the LUA side, it will have to enable and update the status for the checkbox again.

Exactly. It will just help prevent things from going funky if a dialog box gets missed by the user, or the user deliberately ignores it. 

> Which text would you want centred exactly? The titles? or just the paragraphs?

I'd like the main body text to be vertically centred between the logo and the top and the buttons at the bottom. In the case of the "complete" panel - I'd vertically centre the title and the paragraphs.

Let me know if you want me to tackle any of this stuff. I should FINALLY have a bit more time to play around this week (fingers crossed!).

**Comment by latenitefilms** [comment]
@randomeizer - I'm not really sure the best way to tackle "Disabling Prefs checkbox while waiting for LUA to finish" - so I might leave this one for you to do.

With "Reloading/resetting CP after Hacks Shortcuts is changed in Prefs" - there must be a way to do this without having to reload CommandPost?

**Comment by randomeizer** [comment]
Not really at the moment unfortunately. It will require some serious
rewriting in cp.commands to change, so I'd rather make it a separate issue.

**Comment by randomeizer** [comment]
I've added #651 to improve the shortcut/reload issue.

**Comment by latenitefilms** [comment]
@randomeizer - Shall we do "Disabling Prefs checkbox while waiting for LUA to finish" in a seperate issue as well, so we can close off this issue?

**Comment by randomeizer** [comment]
Yeah, sounds good.

**Pull request merged**
