### PR TITLE
Fixed a logic bug in Stream Deck & Resolve Banks

### LINKED ISSUE #3147: Stream Deck (XL) not changing banks
Whenever assigning an action to a button on Stream Deck (XL), or within FCP (HUD) to go to the next or previous bank the information is displayed but the bank is not actually changing on the Stream Deck (XL) itself. 

Going to Control Surfuces -> Stream Deck -> Choose bank does however work. I'm only using one unit (1).

### PR DESCRIPTION
**Pull request by latenitefilms**
- We were working out the bank ID too early.
- Thanks for reporting [@aj752](https://github.com/aj752)
- Thanks for reporting [@KotzendesEinhorn-rgb](https://github.com/KotzendesEinhorn-rgb)
- Closes [#3147](https://github.com/CommandPost/CommandPost/issues/3147)

### CODE REVIEW

**Comment by cheapest-energy-windows** [comment]
I tried the beta just now but for me the behaviour stays the same. I did a uninstall and re-install with the beta but no luck.

**Comment by latenitefilms** [comment]
Can you take a screenshot of your Resolve Control Surfaces panel with the button selected that you're using to change banks?

**Comment by cheapest-energy-windows** [comment]
Sure thing, I tried Next, Previous and also directly to a specific bank. Like mentioned before I also noticed a difference in executing a script directly from the Script Pane and assigning it and pushing the button on the Stream Deck XL. The Stream Deck XL misses commands from the start of the script and therefore fails to execute scripts successfully (no error though).

Screenshot 2023-02-14 at 19 57 06

**Comment by latenitefilms** [comment]
Ummm... I think the problem is that the screen contents thinks it's in one bank (ie bank 2), but the actual button presses think its in another bank (ie bank 1), so it looks right on the screen, but when you press the button nothing happens?

**Comment by cheapest-energy-windows** [comment]
Nothing happens, I do get the "pop-up"saying changing to X bank - but it doesn't actually change. If I keep pressing, the pop-up will keep counting correctly but there is nothing happening on the stream deck itself.

**Comment by cheapest-energy-windows** [comment]
Oke I found something that could be related to what I mentioned earlier, about the Stream Deck missing some commands from the snippet. The exact same behaviour is observed from the Scripting Tools section if you click directly on "Execute Code" when the preference windows is out of focus. IF you click on the Preference window first, to make it active and then click "Execute Code", the snippet executes correctly from the Scripting Tools window. I didn't understand why sometimes my Snippets didn't work, and sometimes they did - this is why. Hope this is of any help for further improvement.

**Comment by latenitefilms** [comment]
Can you take a screenshot of your Stream Deck Control Surfaces panel with the button selected that you're using to change banks?

It sounds like maybe you have opposite issue to what I described, maybe your button actions are correct, but the screen is not updating correctly?

Also, with the Snippets window, are you programming your Stream Deck in the "Ignored and Unlisted Applications"? Is the CommandPost application ignored?

**Comment by cheapest-energy-windows** [comment]
Sure thing, I tried every combination possible.

Application: FCP, CommandPost and Ignored and Unlisted Applications. The "Ignore Application" checkbox has also been part of the combinations tried. I also tried to assign it to different buttons and different banks - all have the same outcome, the commands do not start registering until the lua snippet is already steps ahead. 

Screenshot 2023-02-16 at 14 00 24

**Comment by latenitefilms** [comment]
Can you share a screenshot of the entire window so I can see what settings you have ticked at the top?

**Comment by cheapest-energy-windows** [comment]
Sure, this was on a different bank but those settings don't change. Btw, would be happy to do a share screen and just walk you through if that would be of any help.

Screenshot 2023-02-16 at 20 12 02

**Comment by latenitefilms** [comment]
Have you deliberately got **Automatically Switch Applications** turned off? This will mean that when you change applications (i.e. from Finder to Final Cut Pro) CommandPost won't automatically change applications, and you'll need to use a change application action to upload the Stream Deck.

Have you deliberately got **Preview Selected Application & Bank on Hardware** ticked? All this does is basically "force" the Stream Deck to use whatever application and bank you have selected in the Control Surface panel (i.e. in your screenshot it would be Final Cut Pro Bank 2).

**Comment by cheapest-energy-windows** [comment]
The setting Automatically Switch Applications didn't change anything in this case. The Preview option I enabled once and didn't actually think about it again, I disabled it.

Before I continu wasting your time, I tried to do only like a command+2 to enter timeline in a Snippet and that works, also from a assigned button on my Stream Deck. The Snippet I created is 100+ lines, I'm trying to automate many actions, it starts also with a command+2 but it just doesn't react until later. Am I just pushing it too much maybe?

**Comment by latenitefilms** [comment]
Just to confirm... changing banks is now working, but you have an Snippet that you're trying to trigger from a Stream Deck XL that's not doing anything, is that correct?

Can you try adding:

```
print("Running Snippet")
```

To the top of your Snippet to see if it's being triggered in the Debug Console?

The complexity of the Snippet shouldn't matter/have any impact, and you should get some kind of error in the Debug Console if it fails.

**Comment by cheapest-energy-windows** [comment]
Yes changing banks is working properly! Super useful. 

It doesn't trigger anything extra in the console, it only prints what you put between the quotes. Wasn't sure so I also tried using the Snippet name between quotes. Without quotes it gives an error.

Working from the scripting tools pane is fine for me if there is no other solution, the Snippets saved me from editing hell and still super happy with it. This is my Snippet btw, I don't do anything special I think. Just a bunch of keystrokes and cp.triggers to add some effects and so on.

```lua
local fcp               = require "cp.apple.finalcutpro"
local eventtap          = require "hs.eventtap"
local keyStroke         = eventtap.keyStroke

fcp:launch()

keyStroke({}, "W")
cp.just.wait(3)
keyStroke({"cmd"}, "2")
cp.just.wait(3)
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
cp.just.wait(3)
keyStroke({}, "c")
keyStroke({}, "O")
keyStroke({}, "O")
keyStroke({}, "O")
cp.just.wait(3)
keyStroke({}, "P")
cp.just.wait(3)
keyStroke({"ctrl"}, "d")
keyStroke({}, "-")
keyStroke({}, "3")
keyStroke({}, "0")
keyStroke({}, "0")
keyStroke({}, "return")
cp.just.wait(3)
keyStroke({}, "P")
keyStroke({"ctrl"}, "d")
keyStroke({}, "5")
keyStroke({}, "0")
keyStroke({}, "0")
keyStroke({}, "return")
cp.just.wait(3)
keyStroke({}, "n")
keyStroke({"cmd"}, "r")
cp.just.wait(3)
keyStroke({"cmd"}, "c")
cp.just.wait(3)
keyStroke({}, "m")
keyStroke({"cmd"}, "v")
cp.just.wait(3)
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "c")
keyStroke({}, "o")
keyStroke({}, "o")
keyStroke({}, "o")
keyStroke({"ctrl"}, "d")
keyStroke({}, "1")
keyStroke({}, "0")
keyStroke({}, "0")
keyStroke({}, "0")
keyStroke({}, "return")
cp.just.wait(3)

keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "c")
cp.just.wait(3)
cp.triggerAction("fcpx_videoEffect",{category="AJ Grid Presets",theme="Final Cut",locale="en",name="4-1-S",type="videoEffect",path=[[/Users/aj752/Library/Application Support/ProApps/Effects Presets/4-1-S.effectsPreset]]})
cp.just.wait(3)

keyStroke({"cmd"}, "2")
keyStroke({}, "m")
keyStroke({}, "c")
cp.just.wait(3)
cp.triggerAction("fcpx_videoEffect",{category="AJ Grid Presets",theme="Final Cut",locale="en",name="4-2-S",type="videoEffect",path=[[/Users/aj752/Library/Application Support/ProApps/Effects Presets/4-2-S.effectsPreset]]})
cp.just.wait(3)

keyStroke({"cmd"}, "2")
keyStroke({"cmd"}, "x")
keyStroke({}, "n")
keyStroke({"option"}, "v")
cp.just.wait(3)

keyStroke({}, "c")
cp.just.wait(3)
cp.triggerAction("fcpx_videoEffect",{type="videoEffect",locale="en",path=[[/Users/aj752/Library/Application Support/ProApps/Effects Presets/4-3-S.effectsPreset]],category="AJ Grid Presets",name="4-3-S",theme="Final Cut"})
cp.just.wait(3)

keyStroke({"cmd"}, "2")
keyStroke({"cmd"}, "x")
keyStroke({}, "n")

keyStroke({"option"}, "v")
cp.just.wait(3)

keyStroke({}, "c")
cp.just.wait(3)
cp.triggerAction("fcpx_videoEffect",{locale="en",path=[[/Users/aj752/Library/Application Support/ProApps/Effects Presets/4-4-S.effectsPreset]],category="AJ Grid Presets",type="videoEffect",name="4-4-S",theme="Final Cut"})
cp.just.wait(3)

keyStroke({"cmd"}, "2")
keyStroke({"cmd"}, "x")
keyStroke({}, "n")
keyStroke({"option"}, "v")
cp.just.wait(3)


keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "c")
keyStroke({}, "u")
cp.just.wait(3)
keyStroke({"cmd"}, "t")
cp.just.wait(3)

keyStroke({}, "end")
cp.just.wait(3)

cp.triggerAction("fcpx_title",{path=[[/Users/aj752/Movies/Motion Templates.localized/Titles.localized/AJ Titles/resolution]],category="AJ Titles",type="title",name="resolution",locale="en"})
cp.just.wait(3)

keyStroke({"cmd"}, "2")
cp.just.wait(3)
keyStroke({}, "n")
keyStroke({}, "c")
keyStroke({"ctrl"}, "d")
keyStroke({}, "3")
keyStroke({}, "0")
keyStroke({}, "0")
keyStroke({}, "0")
keyStroke({}, "return")
cp.just.wait(3)

keyStroke({"cmd"}, "x")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({}, "n")
keyStroke({"option"}, "v")

keyStroke({}, "c")
keyStroke({}, "delete")
```

**Comment by latenitefilms** [comment]
Did you try adding:

```lua
print("Running Snippet")
```

...as the first line of the Snippet, to see if it's being triggered?

**Comment by aj752** [comment]
Yes I did, it is not on the example I posted. I mentioned in the comment before that there was no trigger, it only prints whatever is between the quotes on the console.

**Comment by cheapest-energy-windows** [comment]
Yes it does, both with the Stream Deck button and from the Scripting pane. The weird part to me is that it triggers after the last action of the Snippet is finished. 

Stream Deck: it doesn't execute correctly and prints on console after last action of the Snippet.
Scripting Pane: Executes correctly if I first activate the windows, then click execute code. And than prints after last action of the Snippet.

**Comment by latenitefilms** [comment]
Weird. It must be some kind of timing issue.

Maybe try something like this at the start:

```lua
if not cp.just.doUntil(function()
    cp.apple.finalcutpro:launch()
    return cp.apple.finalcutpro:isFrontmost()
end, 5, 0.1) then
    print("Failed to switch back to Final Cut Pro.")
    return
end

print("final cut pro active!")
```

**Comment by cheapest-energy-windows** [comment]
Behaviour stays the same, the snippet "runs" (not correctly because it skips multiple commands at the start and than after the last action it prints "final cut pro active!".

Like I mentioned before, it would obviously be way easier to use it from a button or not having to activate the windows before clicking on executing code (making it more reliable/user friendly)  but it is workable for me. It saves me a tremendous amount of time. I don't want to waste any more of your time, I feel bad already. I do truly appreciate it you trying to help out. Thanks again.

**Comment by cheapest-energy-windows** [comment]
I solved this for my workflow by using hotkeys from stream deck itself and configuring action keys from CP. It works much faster combining the both. Wished there were more action keys, like a 100 instead of 50, could you consider that as a feature request? Thanks.

**Pull request merged**
