### PR TITLE
IFTTT integration

### PR DESCRIPTION
**Pull request by JFtechOfficial**
User needs to create his/her applet on [IFTTT](https://ifttt.com/) for this to work. This plugin uses the webhook channel API and the user defined webhook event name to trigger the applet. It can be used to forward a notification to iOS/Android devices or to trigger other smart automations.

This is my first Lua experiment btw, the source code is pretty simple, I just modified the CP Pushover plugin 😁

### CODE REVIEW

**Comment by latenitefilms** [comment]
Amazing! Thanks heaps @JFtechOfficial !

We'll test it out ASAP.

**Comment by latenitefilms** [comment]
@JFtechOfficial - Ok, so I have absolutely no idea how to set things up on the IFTTT side, so we might need some instructions from you on how exactly to get it all working on the IFTTT site.

**Comment by JFtechOfficial** [comment]
Of course, here is an over-detailed guide on how to setup a simple notification applet from a desktop browser. Notifications will be received on any mobile device with the IFTTT app installed.

### 1. Get the Webhook API Key:
1. go to **IFTTT** and signup / login
2. click on **Explore**
3. search for "_webhooks_" and switch to the **Services** tab
4. click on **Webhooks**
5. click on **Connect** if needed
6. click on **Settings** in the top left corner
7. copy the Webhook API key or the entire URL (the plugin will parse it and extract the key)

### 2. Create a new applet:
1. click on your profile picture
2. click on **Create**
3. click on **+ This** 
4. search **Webhooks** and select it
5. select **Receive a web request**
6. write an event name you like (without spaces). e.g.: _CommandPost_
7. click on **Create trigger**
8. click on **+ Then** 
9. search **Notifications** and select it
10. select **Send a notification from the IFTTT app**
11. customise the message as you like changing text and adding ingredients (_value3_ is unused by the plugin)
12. click on **Create Action**
13. click on **Finish**. You can modify or delete the applet by clicking on **Settings** in the top left corner

### 3. Connect to CommandPost:
1. open **CommandPost**
2. open the **Notification** section (make sure you have the plugin enabled)
3. enable **IFTTT integration**
4. write the same event name as before in the **Webhook Event Name** field. e.g.: _CommandPost_
5. paste the Webhook API key or the entire URL (the plugin will parse it and extract the key) in the **Webhook API key** field
6. click on **Send Text Notification** to check the correctness of the setup.

**Comment by latenitefilms** [comment]
Awesome, thanks heaps! We'll include this in the next release.

**Pull request merged**
