### PR TITLE
Feature/issue 733

### PR DESCRIPTION
**Pull request by randomeizer**

### CODE REVIEW

**Comment by randomeizer** [comment]
Can you think of anything else we should be clearing?

**Comment by latenitefilms** [comment]
We could trash the WebView caches as well I guess?

`~/Library/Caches/org.latenitefilms.CommandPost`

**Comment by randomeizer** [comment]
What generates those? I'm generally trying to keep the extension/plugging
that creates the stuff cleans up after itself.

In this case, it's created by CP.app itself?

**Comment by latenitefilms** [comment]
I think the macOS Frameworks create them when you're working with WebKit.

**Comment by randomeizer** [comment]
Hmm. Not sure where the best place is to manage it then...

**Comment by latenitefilms** [comment]
I'm just going to merge this. I reckon we just make a seperate script script (i.e. like `trash_commandpost_preferences.sh`) for doing a hardcore trash of everything for testing purposes.

**Pull request merged**
