### PR TITLE
#501

### PR DESCRIPTION
**Pull request by randomeizer**
Added a `required` property for plugins and improved the documentation for `cp.plugins`.

### CODE REVIEW

**Comment by latenitefilms** [comment]
I wonder if instead of having nothing in the "Action" column of the Plugins list, it should have text saying "Required" - so it's not just an empty space?

**Comment by randomeizer** [comment]
Yeah, probably.

**Comment by randomeizer** [comment]
Updated to display "Required". How is the rest looking?

By the way, this is currently not guaranteeing that every plugin that can break CP is 'required'. I think that the 'Welcome' panel should be required (currently), but because it has a dependency on `finalcutpro.hacks.shortcuts`, which in turn has dependencies on several other plugins, it all gets a bit messy. I want to tidy it up in #520, which will then make it simpler to lock down the actual required plugins.

**Comment by latenitefilms** [comment]
Yep - all looks great!

Feel free to Merge once you're happy!

**Pull request merged**
