### PR TITLE
Migrated `clipboard.history` and `clipboard.shared`

### PR DESCRIPTION
**Pull request by randomeizer**
Things to test:
* Enabling/Disabling Clipboard History/Shared Clipboard/XML Sharing
* Copying items puts them in history and/or shared clipboard with the hostname
* XML Sharing works correctly
* 'Copy with Custom Label' command works
* 'Copy with Custom Label and Folder' command works.

### CODE REVIEW

**Comment by randomeizer** [comment]
This resolves #233 and #234

**Comment by latenitefilms** [comment]
Awesome work!

Fixed a bug in the XML sharing (`hs.host` wasn't declared).

There doesn't seem to be any way to change the Shared Clipboard path? Toggling the Shared Clipboard on and off doesn't seem to open the path selecting dialog box any more?

I'm getting this error in the console when I copy things - which is obviously not an issue, and doesn't affect anything, but probably shouldn't come up as an error in the console?

```
2017-01-30 06:21:37: ********
 > ERROR: plist: The provided path was not found: /Users/latenitechris/Desktop/FCPX Hacks Shared Clipboard/LateNite Chris.fcpxhacks [06:21:37]
2017-01-30 06:21:37: ********
```

Apart from that, all seems to work as advertised! Moving the "Clear Shared Clipboard" into the individual "folders" is a great idea too - nice work!

**Comment by randomeizer** [comment]
Yeah, we should avoid the error message. I changed the format we save the shared clipboard to JSON, since it's simpler to work with in code (don't have to have tonnes of XML code for plists), but wanted to be able to migrate the old plist versions if present. The error is currently in the 'hs.plist' module, because I'm asking it to load a file that doesn't exist. We should probably just make it a 'warning' at most, but perhaps not even that, if we allow returning 'nil' for non-existent files.

Alternately, we check for the existence of the file before calling plist.

With regards to setting the path, it should be doing it. There must be a logic issue somewhere in the code. I'll see if I can take a look shortly.

**Comment by latenitefilms** [comment]
Error:

```
2017-01-31 08:01:21: ********
 > ERROR:   LuaSkin: hs.menubar:setClickCallback() callback error: ...s/.hammerspoon/hs/fcpxhacks/plugins/clipboard/shared.lua:109: ERROR: incorrect type 'nil' for argument 1 (expected string)
stack traceback:
	[C]: in function 'hs.fs.internal.pathToAbsolute'
	...s/.hammerspoon/hs/fcpxhacks/plugins/clipboard/shared.lua:109: in field 'getFolderNames'
	...s/.hammerspoon/hs/fcpxhacks/plugins/clipboard/shared.lua:300: in field 'itemsFn'
	...ammerspoon/hs/fcpxhacks/plugins/menu/manager/section.lua:162: in function 'hs.fcpxhacks.plugins.menu.manager.section.generateMenuTable'
	...ammerspoon/hs/fcpxhacks/plugins/menu/manager/section.lua:109: in field 'itemFn'
	...ammerspoon/hs/fcpxhacks/plugins/menu/manager/section.lua:152: in function 'hs.fcpxhacks.plugins.menu.manager.section.generateMenuTable'
	...ammerspoon/hs/fcpxhacks/plugins/menu/manager/section.lua:157: in function 'hs.fcpxhacks.plugins.menu.manager.section.generateMenuTable'
	(...tail calls...) [08:01:21]
2017-01-31 08:01:21: ********
2017-01-31 08:01:21: ********
 > ERROR:   LuaSkin: hs.menubar:setMenu() callback must return a valid table [08:01:21]
2017-01-31 08:01:21: ********
2017-01-31 08:01:35: ********
 > ERROR:   LuaSkin: hs.menubar:setClickCallback() callback error: ...s/.hammerspoon/hs/fcpxhacks/plugins/clipboard/shared.lua:109: ERROR: incorrect type 'nil' for argument 1 (expected string)
stack traceback:
	[C]: in function 'hs.fs.internal.pathToAbsolute'
	...s/.hammerspoon/hs/fcpxhacks/plugins/clipboard/shared.lua:109: in field 'getFolderNames'
	...s/.hammerspoon/hs/fcpxhacks/plugins/clipboard/shared.lua:300: in field 'itemsFn'
	...ammerspoon/hs/fcpxhacks/plugins/menu/manager/section.lua:162: in function 'hs.fcpxhacks.plugins.menu.manager.section.generateMenuTable'
	...ammerspoon/hs/fcpxhacks/plugins/menu/manager/section.lua:109: in field 'itemFn'
	...ammerspoon/hs/fcpxhacks/plugins/menu/manager/section.lua:152: in function 'hs.fcpxhacks.plugins.menu.manager.section.generateMenuTable'
	...ammerspoon/hs/fcpxhacks/plugins/menu/manager/section.lua:157: in function 'hs.fcpxhacks.plugins.menu.manager.section.generateMenuTable'
	(...tail calls...) [08:01:35]
2017-01-31 08:01:35: ********
2017-01-31 08:01:35: ********
 > ERROR:   LuaSkin: hs.menubar:setMenu() callback must return a valid table [08:01:35]
2017-01-31 08:01:35: ********
```

**Comment by randomeizer** [comment]
That one should be fixed. Have another go when you get a chance.

**Pull request merged**
