### PR TITLE
middleclass improvements

### LINKED ISSUE #2249: Fix issue with `name` properties in `middleclass` instances
Currently, defining a method or value in a `middleclass` class called `name` will not work as expected, because middleclass sets that value as the class name.

### LINKED ISSUE #2250: `cp.lazy` values are ignored if a class defines a `__index` function

### LINKED ISSUE #2251: Update Tangent Manager to use `middleclass`
Currently it uses a more manual method of inheriting methods and values for `names`. Switching to `middleclass` will make it more consistent.

### PR DESCRIPTION
**Pull request by randomeizer**
Fixes #2249 - now allows classes to have `name` properties/methods
Fixes #2250 - classes with __index defined still support lazy.
Closes #2251 - Tangent Manager classes now use `middleclass`

### CODE REVIEW

**Comment by latenitefilms** [comment]
@randomeizer - Are you still playing with this, or shall we merge it in?

**Comment by randomeizer** [comment]
Should be fine to merge I think

**Comment by latenitefilms** [comment]
@randomeizer - FYI: this branch breaks CommandPost's Tangent support currently:

```lua
CommandPost v1.0.7 (Build: 5781)

Build Date:                     Jan 23 2020, 10:28:33
macOS Version:                  10.14.6
CommandPost Locale:             en_AU
Current Keyboard Layout:        Australian
Final Cut Pro Path:             /Applications/Final Cut Pro.app
Final Cut Pro Version:          10.4.8
Final Cut Pro Language:         en
Developer Mode:                 true

2020-02-09 13:58:22: 2020-02-09 13:58:20: -- Loading /Users/chrishocking/Github/CommandPost/src/extensions/cp/init.lua
2020-02-09 13:58:20: -- Loading extension: hs.uielement
2020-02-09 13:58:22: 13:58:22         cp:     Loading Plugins...
2020-02-09 13:58:31: 13:58:31 ** Warning:   plugins: Slow Plugin: finalcutpro.setup.scan (3.11705)
2020-02-09 13:58:32: 13:58:32         cp:     Plugins Loaded.
2020-02-09 13:58:32:                          Startup Time: 5.706876 seconds
2020-02-09 13:58:32: -- Done.
2020-02-09 13:58:40: ********
2020-02-09 13:58:40: 13:58:40 ERROR:     block: Error while processing cp.web.block: ...ub/CommandPost/src/plugins/core/tangent/manager/mode.lua:110: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
	[C]: in function 'string.format'
	...ub/CommandPost/src/plugins/core/tangent/manager/mode.lua:110: in method 'xml'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:125: in upvalue 'content'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:54: in function <...cking/Github/CommandPost/src/extensions/cp/web/block.lua:52>
	(...tail calls...)
	[C]: in function 'xpcall'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:128: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'post'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:150: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in function <...cking/Github/CommandPost/src/extensions/cp/web/block.lua:67>
	(...tail calls...)
	[C]: in function 'xpcall'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:128: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'post'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:150: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:176: in field 'writeControlsXML'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:643: in field '_set'
	...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:538: in function <...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:525>
	(...tail calls...)
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:669: in function <...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:668>
2020-02-09 13:58:40: ********
2020-02-09 13:58:40: ********
2020-02-09 13:58:40: 13:58:40 ERROR:     block: Error while processing cp.web.block: ...ommandPost/src/plugins/core/tangent/manager/controls.lua:235: attempt to compare two function values
stack traceback:
	...ommandPost/src/plugins/core/tangent/manager/controls.lua:235: in function <...ommandPost/src/plugins/core/tangent/manager/controls.lua:235>
	(...tail calls...)
	[C]: in function 'table.sort'
	...king/Github/CommandPost/src/extensions/cp/tools/init.lua:282: in function 'cp.tools.spairs'
	...ommandPost/src/plugins/core/tangent/manager/controls.lua:235: in upvalue 'content'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:54: in function <...cking/Github/CommandPost/src/extensions/cp/web/block.lua:52>
	(...tail calls...)
	[C]: in function 'xpcall'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:128: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'post'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:150: in function 'cp.web.block.__tostring'
	...
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in function <...cking/Github/CommandPost/src/extensions/cp/web/block.lua:67>
	(...tail calls...)
	[C]: in function 'xpcall'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:128: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'post'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:150: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:176: in field 'writeControlsXML'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:643: in field '_set'
	...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:538: in function <...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:525>
	(...tail calls...)
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:669: in function <...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:668>
2020-02-09 13:58:40: ********
2020-02-09 13:58:40: ********
2020-02-09 13:58:40: 13:58:40 ERROR:     block: Error while processing cp.web.block: ...ub/CommandPost/src/plugins/core/tangent/manager/mode.lua:110: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
	[C]: in function 'string.format'
	...ub/CommandPost/src/plugins/core/tangent/manager/mode.lua:110: in method 'xml'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:125: in upvalue 'content'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:54: in function <...cking/Github/CommandPost/src/extensions/cp/web/block.lua:52>
	(...tail calls...)
	[C]: in function 'xpcall'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:128: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'post'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:150: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'v'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:133: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'post'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:150: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:176: in field 'writeControlsXML'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:643: in field '_set'
	...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:538: in function <...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:525>
	(...tail calls...)
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:669: in function <...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:668>
2020-02-09 13:58:40: ********
2020-02-09 13:58:40: ********
2020-02-09 13:58:40: 13:58:40 ERROR:     block: Error while processing cp.web.block: ...ommandPost/src/plugins/core/tangent/manager/controls.lua:235: attempt to compare two function values
stack traceback:
	...ommandPost/src/plugins/core/tangent/manager/controls.lua:235: in function <...ommandPost/src/plugins/core/tangent/manager/controls.lua:235>
	(...tail calls...)
	[C]: in function 'table.sort'
	...king/Github/CommandPost/src/extensions/cp/tools/init.lua:282: in function 'cp.tools.spairs'
	...ommandPost/src/plugins/core/tangent/manager/controls.lua:235: in upvalue 'content'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:54: in function <...cking/Github/CommandPost/src/extensions/cp/web/block.lua:52>
	(...tail calls...)
	[C]: in function 'xpcall'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:128: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'post'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:150: in function 'cp.web.block.__tostring'
	...
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'v'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:133: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:68: in local 'post'
	...cking/Github/CommandPost/src/extensions/cp/web/block.lua:150: in function 'cp.web.block.__tostring'
	[C]: in function 'tostring'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:176: in field 'writeControlsXML'
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:643: in field '_set'
	...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:538: in function <...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:525>
	(...tail calls...)
	...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:669: in function <...ub/CommandPost/src/plugins/core/tangent/manager/init.lua:668>
2020-02-09 13:58:40: ********
2020-02-09 13:58:40:          tangentMan:     Connection To Tangent Hub (127.0.0.1:64246) successfully established.
2020-02-09 13:58:41: 13:58:41                 InitiateComms Received:
2020-02-09 13:58:41:                              Protocol Revision: 6
2020-02-09 13:58:41:                              Number of Panels: 10
2020-02-09 13:58:41:                                  Panel Type: Ripple (0x00110001)
2020-02-09 13:58:41:                                  Panel Type: CP200-BK (0x00030001)
2020-02-09 13:58:41:                                  Panel Type: Arc-FCN (0x00120001)
2020-02-09 13:58:41:                                  Panel Type: Arc-GRD (0x00130001)
2020-02-09 13:58:41:                                  Panel Type: Arc-NAV (0x00140001)
2020-02-09 13:58:41:                                  Panel Type: Element-Tk (0x000c0001)
2020-02-09 13:58:41:                                  Panel Type: Element-Mf (0x000d0001)
2020-02-09 13:58:41:                                  Panel Type: Element-Kb (0x000e0001)
2020-02-09 13:58:41:                                  Panel Type: Element-Bt (0x000f0001)
2020-02-09 13:58:41:                                  Panel Type: Wave (0x000a0001)
```

**Comment by latenitefilms** [comment]
@randomeizer - Pushed some fixes, which seems to have fixed things, but probably worth you reviewing.

**Pull request merged**
