### PR TITLE
issue 970 - Notifications

### LINKED ISSUE #970: Add Accessibility Notifications API to Final Cut Pro Extension

### PR DESCRIPTION
**Pull request by randomeizer**
Fixes #970

* Added Notifier support to Browser + related Libraries/Media/GeneratorsBrowser

To do a test, you can add a 'watch' to any of the `cp.prop` values in `Browser`, `LibrariesBrowser`, `MediaBrowser` or `GeneratorsBrowser`. For example:

```lua
require("cp.apple.finalcutpro"):libraries().isShowing:watch(function(value, self) print("libraries > isShowing: "..tostring(value)) end)
```

Then hide or show the Browser, or switch to Media/Generators and back and see the result logged in the Console.

Note: some comments incorrectly logged as #960

### CODE REVIEW

**Comment by latenitefilms** [comment]
@randomeizer AMAZING! Thanks so much! This is really, really cool.

When testing with: 

```lua
_fcp:viewer().isPlaying:watch(function(value) print(value) end)
```

It seems to always trigger a callback when it starts playing, but SOMETIMES doesn't detect things when you stop playing. I'd say it works correctly 95% of the time, so I'm not sure why it would sometime fail to detect a change? It doesn't seem to be related to how quickly I press spacebar.

Apart from this though, it all seems to be working really well.

Feel free to merge in when you're happy!

**Comment by randomeizer** [comment]
Hmm. Currently, it is updating the 'isPlayed' status when the value changes. Or more accurately, the notification is sent on a timer, so it is at some point *after* the notification. We don't actually get a notification about play stopping. My guess is it works most of the time because there is enough delay after the notification when it has stopped that the icon has changed, but not always.

**Comment by randomeizer** [comment]
So, I've fixed the issue where `Viewer.isPlaying()` was not always returning the correct result. I haven't fixed the potential issue with it not updating correctly when the timecode stops changing. Will have to think about a good solution for that...

**Comment by latenitefilms** [comment]
@randomeizer - Now that we know we can use screen-captures to compare things, we could monitor the colour of the playhead too?

FYI - this seems to work a bit better. I still get the very, very occasional case where it's not detecting the stopping of playback, but seems way less often:

```lua
_fcp:viewer().isPlaying:watch(function(value) 
print(string.format("Playing: %s", value))
hs.timer.doAfter(0.1, function() _fcp:viewer().isPlaying:update() end)
end)
```

Also, if the callback hasn't detected the stop, all I need to do is hover over the timeline (so that the timecode changes), which triggers the callback and updates the correct value. So maybe all we need to do is add a `hs.timer.doAfter` when the timecode has changed?

**Comment by latenitefilms** [comment]
Also, the fact that timecode isn't continuous could be a factor? Are you triggering a callback only if the timecode value changes?

```lua
> _fcp:viewer().timecode:watch(function(value) print(string.format("Timecode: %s", value)) end)
timecode: 12:14:38:11	function: 0x60c000a4cc00
2018-03-05 12:54:01: Timecode: 12:13:56:10
2018-03-05 12:54:01: Timecode: 12:13:56:14
2018-03-05 12:54:02: Timecode: 12:13:57:17
2018-03-05 12:54:02: Timecode: 12:13:58:16
2018-03-05 12:54:02: Timecode: 12:13:59:12
2018-03-05 12:54:02: Timecode: 12:14:00:07
2018-03-05 12:54:02: Timecode: 12:14:00:21
2018-03-05 12:54:02: Timecode: 12:14:01:10
2018-03-05 12:54:02: Timecode: 12:14:01:17
2018-03-05 12:54:02: Timecode: 12:14:01:19
2018-03-05 12:54:02: Timecode: 12:14:01:23
2018-03-05 12:54:02: Timecode: 12:14:38:11
2018-03-05 12:54:02: Timecode: 12:14:02:00
2018-03-05 12:54:03: Timecode: 12:14:02:01
2018-03-05 12:54:03: Timecode: 12:14:02:02
2018-03-05 12:54:03: Timecode: 12:14:02:04
2018-03-05 12:54:03: Timecode: 12:14:02:05
2018-03-05 12:54:03: Timecode: 12:14:02:07
2018-03-05 12:54:03: Timecode: 12:14:02:08
2018-03-05 12:54:03: Timecode: 12:14:02:10
2018-03-05 12:54:03: Timecode: 12:14:02:11
2018-03-05 12:54:03: Timecode: 12:14:02:13
2018-03-05 12:54:03: Timecode: 12:14:02:14
2018-03-05 12:54:03: Timecode: 12:14:02:16
2018-03-05 12:54:03: Timecode: 12:14:02:17
2018-03-05 12:54:03: Timecode: 12:14:02:19
2018-03-05 12:54:03: Timecode: 12:14:02:20
2018-03-05 12:54:03: Timecode: 12:14:02:22
2018-03-05 12:54:04: Timecode: 12:14:02:23
2018-03-05 12:54:04: Timecode: 12:14:03:00
2018-03-05 12:54:04: Timecode: 12:14:03:01
2018-03-05 12:54:04: Timecode: 12:14:03:03
2018-03-05 12:54:04: Timecode: 12:14:03:04
2018-03-05 12:54:04: Timecode: 12:14:03:06
2018-03-05 12:54:04: Timecode: 12:14:03:07
2018-03-05 12:54:04: Timecode: 12:14:03:09
2018-03-05 12:54:04: Timecode: 12:14:03:10
2018-03-05 12:54:04: Timecode: 12:14:03:12
2018-03-05 12:54:04: Timecode: 12:14:03:13
2018-03-05 12:54:04: Timecode: 12:14:03:15
2018-03-05 12:54:04: Timecode: 12:14:03:16
2018-03-05 12:54:04: Timecode: 12:14:03:18
2018-03-05 12:54:04: Timecode: 12:14:03:19
2018-03-05 12:54:04: Timecode: 12:14:03:21
2018-03-05 12:54:04: Timecode: 12:14:03:22
2018-03-05 12:54:05: Timecode: 12:14:03:24
2018-03-05 12:54:05: Timecode: 12:14:04:00
2018-03-05 12:54:05: Timecode: 12:14:04:02
2018-03-05 12:54:05: Timecode: 12:14:04:03
2018-03-05 12:54:05: Timecode: 12:14:04:04
2018-03-05 12:54:33: Timecode: 12:14:04:05
2018-03-05 12:54:33: Timecode: 12:14:04:06
2018-03-05 12:54:33: Timecode: 12:14:04:07
2018-03-05 12:54:33: Timecode: 12:14:04:09
2018-03-05 12:54:33: Timecode: 12:14:04:11
2018-03-05 12:54:33: Timecode: 12:14:04:12
2018-03-05 12:54:34: Timecode: 12:14:04:14
2018-03-05 12:54:34: Timecode: 12:14:04:15
2018-03-05 12:54:34: Timecode: 12:14:04:16
2018-03-05 12:54:34: Timecode: 12:14:04:18
2018-03-05 12:54:34: Timecode: 12:14:04:19
2018-03-05 12:54:34: Timecode: 12:14:04:21
2018-03-05 12:54:34: Timecode: 12:14:04:23
2018-03-05 12:54:34: Timecode: 12:14:04:24
2018-03-05 12:54:34: Timecode: 12:14:05:01
2018-03-05 12:54:34: Timecode: 12:14:05:02
2018-03-05 12:54:34: Timecode: 12:14:05:04
2018-03-05 12:54:34: Timecode: 12:14:05:05
2018-03-05 12:54:34: Timecode: 12:14:05:07
2018-03-05 12:54:34: Timecode: 12:14:05:08
2018-03-05 12:54:34: Timecode: 12:14:05:10
2018-03-05 12:54:34: Timecode: 12:14:05:11
2018-03-05 12:54:34: Timecode: 12:14:05:13
2018-03-05 12:54:35: Timecode: 12:14:05:14
2018-03-05 12:54:35: Timecode: 12:14:05:16
2018-03-05 12:54:35: Timecode: 12:14:05:17
2018-03-05 12:54:35: Timecode: 12:14:05:18
2018-03-05 12:54:35: Timecode: 12:14:05:20
2018-03-05 12:54:35: Timecode: 12:14:05:22
2018-03-05 12:54:35: Timecode: 12:14:05:23
2018-03-05 12:54:35: Timecode: 12:14:06:00
2018-03-05 12:54:35: Timecode: 12:14:06:01
2018-03-05 12:54:35: Timecode: 12:14:06:03
2018-03-05 12:54:35: Timecode: 12:14:06:04
2018-03-05 12:54:35: Timecode: 12:14:06:06
2018-03-05 12:54:35: Timecode: 12:14:06:07
2018-03-05 12:54:35: Timecode: 12:14:06:08
2018-03-05 12:54:35: Timecode: 12:14:06:10
2018-03-05 12:54:35: Timecode: 12:14:06:12
2018-03-05 12:54:35: Timecode: 12:14:06:13
2018-03-05 12:54:36: Timecode: 12:14:06:14
2018-03-05 12:54:36: Timecode: 12:14:06:16
2018-03-05 12:54:36: Timecode: 12:14:06:17
2018-03-05 12:54:36: Timecode: 12:14:06:19
2018-03-05 12:54:36: Timecode: 12:14:06:21
2018-03-05 12:54:36: Timecode: 12:14:06:22
2018-03-05 12:54:36: Timecode: 12:14:06:24
2018-03-05 12:54:36: Timecode: 12:14:07:00
2018-03-05 12:54:36: Timecode: 12:14:07:02
2018-03-05 12:54:36: Timecode: 12:14:07:03
2018-03-05 12:54:36: Timecode: 12:14:07:05
2018-03-05 12:54:36: Timecode: 12:14:03:19
2018-03-05 12:54:36: Timecode: 12:14:02:12
2018-03-05 12:54:36: Timecode: 12:14:00:13
2018-03-05 12:54:37: Timecode: 12:14:07:05
```

**Comment by randomeizer** [comment]
Yeah, it was just watching for timecode `AXValueChange` notifications. I've switched in an `hs.timer.delayed` to keep the number of timers getting created to a minimum. It just runs when prompted by a timecode change, but checks after the change until `isPlaying` is no longer `true`. Let me know if there are any issues.

Also, can you check that `isPlaying` is giving you the correct value for the Viewer and Event Viewer in a variety of locations (primary/secondary display) and with/without Event Viewer on? Also, the resolution (standard, retina, "more space"). It's working for me in the different combinations I can think of.

**Comment by latenitefilms** [comment]
On a single screen, when in "Loop Playback" mode, this doesn't work for me:

```lua
_fcp:eventViewer().isPlaying:watch(function(value) print(string.format("Event: %s", value)) end)
```

If I turn off "Loop Playback" it works fine.

On a single screen, the normal viewer with looped both on and off works fine with this:

```lua
_fcp:viewer().isPlaying:watch(function(value) print(value) end)
```

All of the above tests are using the following screen setting:

screen shot 2018-03-05 at 2 48 23 pm

**Comment by latenitefilms** [comment]
Changing to "Default for Display" has the same results:

screen shot 2018-03-05 at 2 53 18 pm

**Pull request merged**
